[global]
fps = 60    # this is my monitor max refresh rate, change if necessary
debug = false
duration = 0.5
vsync = false
easing = "cubic"

[global.parallax.max_offset_px]
x = 300
y = 150

[[global.layers]]
path = "../../Pictures/EIA-full-upscaled-contrast.jpeg"
shift_multiplier = 1.0
scale = 1.0
fit = "cover"
align = { x = 0, y = 0.5 }